# Generated by Django 3.2.9 on 2021-11-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20211128_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
