# Generated by Django 3.2.9 on 2021-11-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_image_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
